Personal/elliswilson/numerous copytool fixes
wastore/lemur pull request #60
Opened 2023-09-28 21:16 UTC by ellis-wilson-ms

2023-10-04 18:24 UTC, cyrus-ramavarapu-ms approved these changes

2023-10-05 15:37 UTC, tong-xiao-ms requested changes

2023-10-05 16:43 UTC, cyrus-ramavarapu-ms requested changes

2023-10-05 16:43 UTC, cyrus-ramavarapu-ms commented on cmd/lhsmd/agent/action_stats.go
> +  if (rc == int(syscall.ECANCELED)) {
I like this too and it feels doable in StartAction with a similar change to what you did in agent_action.go (check for llapi.HsmActionCancel). Imports will need an update as well.

2023-10-05 16:49 UTC, ellis-wilson-ms commented on cmd/lhsm-plugin-az/mover.go
> -	_, srcObj, err := m.fileIDtoContainerPath(action.UUID())
Good catch.  Removed.

2023-10-05 17:17 UTC, ellis-wilson-ms commented on cmd/lhsmd/agent/action_stats.go
> +  if (rc == int(syscall.ECANCELED)) {
@cyrus-ramavarapu-ms and @tong-xiao-ms : the reason why I'd like to preserve a cancel action showing up in the queue length is for debugability.  At present all we really get out of the copytool during normal non-error function is:

Oct  5 17:15:38 cb3b6dd2-b409-4c9f-9461-49f67887d1e9-agtpri-a0-vm lhsmd[10760]: 2023/10/05 17:15:38 lhsm-plugin-az2 2023/10/05 17:15:38 total 562,702 (1 min/5 min/15 min/inst): 102/99/97/75 msg/sec
Oct  5 17:15:38 cb3b6dd2-b409-4c9f-9461-49f67887d1e9-agtpri-a0-vm lhsmd[10760]: 2023/10/05 17:15:38 archive:1 total:562,701 queue:1 102/99/97 min:88.310232ms max:744.263542ms mean:366.051947ms median:360.63731ms 75%:500.732598ms 95%:588.236959ms 99%:705.947727ms 99.9%:743.835803ms

If a cancel comes in and somehow gets stuck canceling an archive or restore, then at least I will see that there are two commands in the queue.  In the absence of that lone breadcrumb cancels become totally silent actions.

Accordingly, I'd like to punt on this change request.  Please let me know if either of you object.

2023-10-05 17:17 UTC, ellis-wilson-ms commented on cmd/lhsmd/agent/agent_action.go
> -			createSnapshot(action.agent.Root(), action.aih.ArchiveID(), action.aih.Fid(), []byte(status.Uuid))
Good point.  None of the rest of the code uses snapshots or any functions herein anymore, so I've completely blown away the file.

2023-10-05 17:20 UTC, ellis-wilson-ms commented on cmd/lhsmd/agent_e2e_test.go
> -	fileid.EnableTestMode()
No.  I removed all support for File Attributes, so there's no longer a need for the test mode.

2023-10-05 17:43 UTC, tong-xiao-ms approved these changes

2023-10-05 17:44 UTC, cyrus-ramavarapu-ms approved these changes

2023-10-05 19:32 UTC, merged